/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as featuresVolunteersRouteImport } from './routes/(features)/volunteers'
import { Route as featuresReportsRouteImport } from './routes/(features)/reports'
import { Route as featuresDonationsRouteImport } from './routes/(features)/donations'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const featuresVolunteersRoute = featuresVolunteersRouteImport.update({
  id: '/(features)/volunteers',
  path: '/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const featuresReportsRoute = featuresReportsRouteImport.update({
  id: '/(features)/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const featuresDonationsRoute = featuresDonationsRouteImport.update({
  id: '/(features)/donations',
  path: '/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/donations': typeof featuresDonationsRoute
  '/reports': typeof featuresReportsRoute
  '/volunteers': typeof featuresVolunteersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/donations': typeof featuresDonationsRoute
  '/reports': typeof featuresReportsRoute
  '/volunteers': typeof featuresVolunteersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(features)/donations': typeof featuresDonationsRoute
  '/(features)/reports': typeof featuresReportsRoute
  '/(features)/volunteers': typeof featuresVolunteersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/donations'
    | '/reports'
    | '/volunteers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/donations'
    | '/reports'
    | '/volunteers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(features)/donations'
    | '/(features)/reports'
    | '/(features)/volunteers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  featuresDonationsRoute: typeof featuresDonationsRoute
  featuresReportsRoute: typeof featuresReportsRoute
  featuresVolunteersRoute: typeof featuresVolunteersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(features)/volunteers': {
      id: '/(features)/volunteers'
      path: '/volunteers'
      fullPath: '/volunteers'
      preLoaderRoute: typeof featuresVolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(features)/reports': {
      id: '/(features)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof featuresReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(features)/donations': {
      id: '/(features)/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof featuresDonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  featuresDonationsRoute: featuresDonationsRoute,
  featuresReportsRoute: featuresReportsRoute,
  featuresVolunteersRoute: featuresVolunteersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
